"""add trigger status to alerts

Revision ID: 53dccd2b8e87
Revises: 5fdfa76f6e55
Create Date: 2026-09-22 15:09:54.127329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dccd2b8e87'
down_revision: Union[str, Sequence[str], None] = '5fdfa76f6e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_triggered', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('alerts', sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'triggered_at')
    op.drop_column('alerts', 'is_triggered')
    # ### end Alembic commands ###
